// Returns all the food
GET http://localhost:8080/food

// Returns a single food item by food id (steak in this case)
GET http://localhost:8080/food/62326b5bc563adc8d8ec32e6

// Adds a single food item **INCOMPLETE**
POST http://localhost:8080/food/add-food
{
    "calories": "Put number",
    "name": "Put name",
    "description": "Put description",
    "imageURL": ""
}

// Sign up as a user 
PUT http://localhost:8080/auth/signup
{
    "email": "test@email.com",
    "name": "Bri",
    "password": "password"
}

// Login as a user
POST http://localhost:8080/auth/login
{
    "email": "test@email.com",
    "password": "password"
}
/* Returns a token and userId
{"token":"tokenExample123","userId":"userIdExample123"}

Token and userId can then be stored on client (such as in local storage)
Also set an expiration for the token

Send token in headers with requests that require authorization
headers: {Authorization: `Bearer ${token}` } */